Attribute VB_Name = "mdlDelete"
'@Folder "MODULE"
Option Compare Database
Option Explicit

Const ModuleName As String = "mdlDelete"
Private vReturnValue As Variant

'TODO: check all deletes are working - are all references being deleted?

Public Property Let ReturnValue(X As Variant)
    vReturnValue = X
End Property

Public Property Get ReturnValue() As Variant
    ReturnValue = vReturnValue
End Property

Public Function UndoUpdate() As Boolean
    Dim msg As String
    Dim s As String
    Dim SQL As String
    Dim rtn As Integer
    Dim rst As DAO.Recordset
    
    On Error GoTo PROC_ERR
    UndoUpdate = False
    
    s = vbNullString
    s = s & vbCrLf & "This action will result in ...."
    s = s & vbCrLf & " ...The removal of ALL inspection orders with Status 'ACTION'."
    s = s & vbCrLf & " ...('Test' data may also be deleted.)"
    s = s & vbCrLf
    s = s & vbCrLf & "This routine is useful in cleaning up records that inhibit"
    s = s & vbCrLf & " 'enabling' a customer-site LINK. "
    s = s & vbCrLf
    s = s & vbCrLf & "DO YOU REALLY WANT TO ATTEMPT AN UNDO-UPDATE?"
        
    rtn = MsgBox(s, vbYesNo Or vbExclamation Or vbDefaultButton2, "UNDO UPDATE")
    If rtn = vbYes Then
    
            ' iterate over inspection orders and delete test results
        SQL = "SELECT * FROM dbo_InspectionOrder WHERE ((dbo_InspectionOrder.InspectionStatusID)=1) "
        Set rst = CurrentDb.OpenRecordset(SQL, dbOpenSnapshot, dbFailOnError + dbSeeChanges)
        If rst.RecordCount > 0 Then
            Do While Not rst.EOF
               SQL = "DELETE * FROM dbo_Test WHERE [InspectionOrderID] = " & CStr(rst![InspectionOrderID])
               CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
               rst.MoveNext
            Loop
        End If
        rst.Close
        Set rst = Nothing
    
        ' DELETE InspectionStatusID = 1
        SQL = _
        "Delete dbo_InspectionOrder.* FROM dbo_InspectionOrder WHERE ((dbo_InspectionOrder.InspectionStatusID)=1)"
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
    
        UndoUpdate = True
        MsgBox "The Undo-Update was completed!", vbOKOnly, "UNDO UPDATE"
    
    End If

PROC_EXIT:
    On Error Resume Next
    Exit Function

PROC_ERR:
    ' display the system error
    If err.Number <> 0 Then
        msg = ModuleName & " UndoUpdate" & vbCrLf & _
              "Error # " & CStr(err.Number) & " was generated by " & err.SOURCE & vbCrLf & err.Description
        MsgBox msg, , "Error", err.HelpFile, err.HelpContext
    End If
    
    Resume PROC_EXIT

End Function

Public Function DeleteEquipment() As Boolean
    Dim msg As String
    Dim s As String
    Dim frm As Form
    Dim mOpenArgs As String
    Dim SQL As String
    Dim v As Variant
    Dim rtn As Integer
    Dim rst As DAO.Recordset

    On Error GoTo PROC_ERR
    
    mOpenArgs = "DELETE EQUIPMENT"
    DeleteEquipment = False
    
    ' Go grab the ID
    DoCmd.OpenForm "xDlgGoto_DELETE_ID", , , , , acDialog, mOpenArgs
    DoCmd.Close acForm, "xDlgGoto_DELETE_ID"
    
    If (Nz(vReturnValue, 0) > 0) Then
        v = DLookup("[EquipmentID]", "dbo_Equipment", "[EquipmentID] = " & CStr(vReturnValue))
        If IsNull(v) Then
            'The Equipment ID doesn't exist.
            Beep
            MsgBox "The Equipment doesn't exist", vbOKOnly, "DELETE EQUIPMENT FAILED"
            Exit Function
        End If
    Else
        ' NULL VALUE EXIT
        Exit Function
    End If
            
    s = vbNullString
    s = "Equipment ID: " & Format(CStr(vReturnValue), "0000")
    ' ----------------------------------
    ' FIX EXCEPTION ERROR ON NULL MISSIN CAPTION
    v = DLookup("[Caption]", "dbo_Equipment", "[EquipmentID] = " & CStr(vReturnValue))
    If Not IsNull(v) Then
        s = s & " " & CStr(v)
    Else
        s = s & " A description wasn't entered for this equipment."
    End If
    s = s & vbCrLf
    s = s & vbCrLf & "This action will result in ...."
    s = s & vbCrLf & " ...REMOVE ALL references in Stations (make EMPTY)."
    s = s & vbCrLf & " ...DELETE ALL Tests that reference the equipment."
    s = s & vbCrLf
    s = s & vbCrLf & "DO YOU REALLY WANT TO DELETE THE EQUIPMENT?"
        
    rtn = MsgBox(s, vbYesNo Or vbExclamation Or vbDefaultButton2, "DELETE EQUIPMENT")
    If rtn = vbYes Then
    
        ' iterate over stations and NULL equipment and SET state of IsManaged and IsEmpty results
        SQL = "UPDATE dbo_Station SET [IsEmpty]=1,[IsManaged]=0,[EquipmentID]=NULL WHERE [EquipmentID]= " & CStr(vReturnValue)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
        
        ' DELETE ALL TESTs that reference the equipment
        SQL = "DELETE * FROM dbo_Test WHERE [EquipmentID] = " & CStr(vReturnValue)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
    
        ' DELETE .. DELETE .. DELETE .. DELETE .. DELETE .. DELETE
        SQL = "DELETE * FROM dbo_Equipment WHERE [EquipmentID] = " & CStr(vReturnValue)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
    
        DeleteEquipment = True
        MsgBox "The EQUIPMENT was DELETED!", vbOKOnly, "DELETE EQUIPMENT"
    
    End If

PROC_EXIT:
    On Error Resume Next
    Exit Function

PROC_ERR:
    ' display the system error
    If err.Number <> 0 Then
        msg = ModuleName & " DeleteEquipment" & vbCrLf & _
              "Error # " & CStr(err.Number) & " was generated by " & err.SOURCE & vbCrLf & err.Description
        MsgBox msg, , "Error", err.HelpFile, err.HelpContext
    End If
    
    Resume PROC_EXIT
End Function


Public Function DeleteSurveyOrder() As Boolean
    Dim msg As String
    Dim s As String
    Dim frm As Form
    Dim mOpenArgs As String
    Dim SQL As String
    Dim v As Variant
    Dim rtn As Integer
    Dim rst As DAO.Recordset

    On Error GoTo PROC_ERR
    
    mOpenArgs = "DELETE SURVEY ORDER"
    DeleteSurveyOrder = False
    
    ' Go grab the ID
    DoCmd.OpenForm "xDlgGoto_DELETE_ID", , , , , acDialog, mOpenArgs
    DoCmd.Close acForm, "xDlgGoto_DELETE_ID"
    
    If (Nz(vReturnValue, 0) > 0) Then
        v = DLookup("[SurveyOrderID]", "dbo_SurveyOrder", "[SurveyOrderID] = " & CStr(vReturnValue))
        If IsNull(v) Then
            'The SurveyOrder ID doesn't exist.
            Beep
            MsgBox "The SurveyOrder doesn't exist", vbOKOnly, "DELETE SURVEY ORDER FAILED"
            Exit Function
        End If
    Else
        ' NULL VALUE EXIT
        Exit Function
    End If
        
    s = vbNullString
    s = Format(CStr(vReturnValue), "0000")
    s = s & vbCrLf
    s = s & vbCrLf & "DO YOU REALLY WANT TO DELETE THE SURVEY ORDER?"
        
    rtn = MsgBox(s, vbYesNo Or vbExclamation Or vbDefaultButton2, "DELETE SURVEY ORDER")
    If rtn = vbYes Then
        ' DELETE .. DELETE .. DELETE .. DELETE .. DELETE .. DELETE
        SQL = "DELETE * FROM dbo_SurveyOrder WHERE [SurveyOrderID] = " & CStr(vReturnValue)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
    
        DeleteSurveyOrder = True
        MsgBox "The Survey Order was DELETED!", vbOKOnly, "DELETE SURVEY ORDER"
    
    End If

PROC_EXIT:
    On Error Resume Next
    Exit Function

PROC_ERR:
    ' display the system error
    If err.Number <> 0 Then
        msg = ModuleName & " DeleteSurveyOrder" & vbCrLf & _
              "Error # " & CStr(err.Number) & " was generated by " & err.SOURCE & vbCrLf & err.Description
        MsgBox msg, , "Error", err.HelpFile, err.HelpContext
    End If
    
    Resume PROC_EXIT
End Function


Public Function DeleteInspectionOrder() As Boolean
    Dim msg As String
    Dim s As String
    Dim frm As Form
    Dim mOpenArgs As String
    Dim SQL As String
    Dim v As Variant
    Dim rtn As Integer
    Dim rst As DAO.Recordset

    On Error GoTo PROC_ERR
    
    mOpenArgs = "DELETE INSPECTION ORDER"
    DeleteInspectionOrder = False
    
    ' Go grab the ID
    DoCmd.OpenForm "xDlgGoto_DELETE_ID", , , , , acDialog, mOpenArgs
    DoCmd.Close acForm, "xDlgGoto_DELETE_ID"
    
    If (Nz(vReturnValue, 0) > 0) Then
        v = DLookup("[InspectionOrderID]", "dbo_InspectionOrder", "[InspectionOrderID] = " & CStr(vReturnValue))
        If IsNull(v) Then
            'The InspectionOrder ID doesn't exist.
            Beep
            MsgBox "The InspectionOrder doesn't exist", vbOKOnly, "DELETE InspectionOrder FAILED"
            Exit Function
        End If
    Else
        ' NULL VALUE EXIT
        Exit Function
    End If
    
    s = vbNullString
    s = "InspectionOrderID: " & Format(CStr(vReturnValue), "0000")
    s = s & vbCrLf & "This action will result in ...."
    s = s & vbCrLf & " ...DELETE ALL InspectionOrder's inspection test results."
    s = s & vbCrLf
    s = s & vbCrLf & "DO YOU REALLY WANT TO DELETE THE INSPECTION ORDER?"
        
    rtn = MsgBox(s, vbYesNo Or vbExclamation Or vbDefaultButton2, "DELETE InspectionOrder")
    If rtn = vbYes Then
        ' iterate over inspection orders and delete test results
        SQL = "SELECT * FROM dbo_InspectionOrder WHERE [InspectionOrderID] = " & CStr(vReturnValue)
        Set rst = CurrentDb.OpenRecordset(SQL, dbOpenSnapshot, dbFailOnError + dbSeeChanges)
        Do While Not rst.EOF
           SQL = "DELETE * FROM dbo_Test WHERE [InspectionOrderID] = " & CStr(rst![InspectionOrderID])
           CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
           rst.MoveNext
        Loop
        rst.Close
        Set rst = Nothing
                         
        ' DELETE .. DELETE .. DELETE .. DELETE .. DELETE .. DELETE
        SQL = "DELETE * FROM dbo_InspectionOrder WHERE [InspectionOrderID] = " & CStr(vReturnValue)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
    
        DeleteInspectionOrder = True
        MsgBox "The Inspection Order was DELETED!", vbOKOnly, "DELETE INSPECTION ORDER"
    
    End If

PROC_EXIT:
    On Error Resume Next
    Exit Function

PROC_ERR:
    ' display the system error
    If err.Number <> 0 Then
        msg = ModuleName & " DeleteInspectionOrder" & vbCrLf & _
              "Error # " & CStr(err.Number) & " was generated by " & err.SOURCE & vbCrLf & err.Description
        MsgBox msg, , "Error", err.HelpFile, err.HelpContext
    End If
    
    Resume PROC_EXIT
End Function


Public Function DeleteSite() As Boolean
    Dim msg As String
    Dim s As String
    Dim frm As Form
    Dim mOpenArgs As String
    Dim SQL As String
    Dim varSiteID As Variant
    Dim varAddress As Variant
    Dim rtn As Integer
    Dim rst As DAO.Recordset
    Dim v As Variant

    On Error GoTo PROC_ERR
    
    mOpenArgs = "DELETE SITE"
    DeleteSite = False
    
    ' Go grab the ID
    DoCmd.OpenForm "xDlgGoto_DELETE_ID", , , , , acDialog, mOpenArgs
    DoCmd.Close acForm, "xDlgGoto_DELETE_ID"
    
    If (Nz(vReturnValue, 0) > 0) Then
        varSiteID = DLookup("[SiteID]", "dbo_Site", "[SiteID] = " & CStr(vReturnValue))
        If IsNull(varSiteID) Then
            'The Site ID doesn't exist.
            Beep
            MsgBox "The Site doesn't exist", vbOKOnly, "DELETE SITE FAILED"
            Exit Function
        End If
    Else
        ' NULL VALUE EXIT
        Exit Function
    End If
    
    s = vbNullString
    s = "SiteID: " & Format(CStr(varSiteID), "0000") & " "
    ' ----------------------------------
    ' FIX EXCEPTION ERROR ON NULL MISSING CAPTION
    varAddress = DLookup("[Address]", "dbo_Site", "[SiteID] = " & CStr(varSiteID))
    If Not IsNull(v) Then
        s = s & " " & CStr(varAddress)
    Else
        s = s & "An address wasn't entered for this site"
    End If
    
    s = s & vbCrLf & "This action will result in ...."
    s = s & vbCrLf & " ...DELETE ALL Test results for each Inspection Order that uses the Site."
    s = s & vbCrLf & " ...DELETE ALL Inspection Orders that uses the Site."
    s = s & vbCrLf & " ...DELETE ALL Site's Stations."
    s = s & vbCrLf & " ...DELETE ALL Site's customer-site LINKs."
    s = s & vbCrLf
    s = s & vbCrLf & "DO YOU REALLY WANT TO DELETE THE SITE?"
        
    rtn = MsgBox(s, vbYesNo Or vbExclamation Or vbDefaultButton2, "DELETE SITE")
    If rtn = vbYes Then
    
        ' ##############  DELETE THE Site
        
        ' Delete ALL Test's
        ' iterate over each Inspection Order - with site id
        SQL = "SELECT dbo_InspectionOrder.InspectionOrderID FROM dbo_InspectionOrder WHERE [SiteID] = " & CStr(varSiteID)
        Set rst = CurrentDb.OpenRecordset(SQL, dbOpenSnapshot, dbFailOnError + dbSeeChanges)
        Do While Not rst.EOF
           SQL = "DELETE * FROM dbo_Test WHERE [dbo_InspectionOrder] = " & CStr(rst![InspectionOrderID])
           CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
           rst.MoveNext
        Loop
        rst.Close
        Set rst = Nothing
        
        ' Delete ALL INSPECTION ORDERS
        SQL = "DELETE * FROM dbo_InspectionOrder WHERE [SiteID] = " & CStr(varSiteID)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
        
        ' Delete ALL POWER BOARDS
        SQL = "DELETE * FROM dbo_PowerBoard WHERE [SiteID] = " & CStr(varSiteID)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
        
        ' Delete ALL STATIONS
        SQL = "DELETE * FROM dbo_Station WHERE [SiteID] = " & CStr(varSiteID)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
                
        ' Delete ALL CustSite LINKS
        SQL = "DELETE * FROM dbo_CustSite WHERE [SiteID] = " & CStr(varSiteID)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
    
        ' DELETE .. DELETE .. DELETE .. DELETE .. DELETE .. DELETE
        SQL = "DELETE * FROM dbo_Site WHERE [SiteID] = " & CStr(varSiteID)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
    
        DeleteSite = True
        MsgBox "The Site was DELETED!", vbOKOnly, "DELETE SITE"
    
    End If

PROC_EXIT:
    On Error Resume Next
    Exit Function

PROC_ERR:
    ' display the system error
    If err.Number <> 0 Then
        msg = ModuleName & " DeleteSite" & vbCrLf & _
              "Error # " & CStr(err.Number) & " was generated by " & err.SOURCE & vbCrLf & err.Description
        MsgBox msg, , "Error", err.HelpFile, err.HelpContext
    End If
    
    Resume PROC_EXIT
End Function




Public Function DeleteCustomer() As Boolean
    Dim msg As String
    Dim s As String
    Dim frm As Form
    Dim mOpenArgs As String
    Dim SQL As String
    Dim v As Variant
    Dim rtn As Integer
    Dim rst As DAO.Recordset

    On Error GoTo PROC_ERR
    
    mOpenArgs = "DELETE CUSTOMER"
    DeleteCustomer = False
    
    ' Go grab the ID
    DoCmd.OpenForm "xDlgGoto_DELETE_ID", , , , , acDialog, mOpenArgs
    DoCmd.Close acForm, "xDlgGoto_DELETE_ID"
    
    If (Nz(vReturnValue, 0) > 0) Then
        v = DLookup("[CustomerID]", "dbo_Customer", "[CustomerID] = " & CStr(vReturnValue))
        If IsNull(v) Then
            'The Customer ID doesn't exist.
            Beep
            MsgBox "The Customer doesn't exist", vbOKOnly, "DELETE Customer FAILED"
            Exit Function
        End If
    Else
        ' NULL VALUE EXIT
        Exit Function
    End If
    
    
    s = vbNullString
    s = "CustomerID: " & Format(CStr(vReturnValue), "0000")
    ' ----------------------------------
    ' FIX EXCEPTION ERROR ON NULL MISSING CAPTION
    v = DLookup("[CustName]", "dbo_Customer", "[CustomerID] = " & CStr(vReturnValue))
    If Not IsNull(v) Then
        s = s & " " & CStr(v)
    Else
        s = s & "A name wasn't entered for this customer"
    End If
    
    s = s & vbCrLf & "This action will result in ...."
    s = s & vbCrLf & " ...DELETE ALL Customer's contact numbers."
    s = s & vbCrLf & " ...DELETE ALL Customer's addresses."
    s = s & vbCrLf & " ...DELETE ALL Customer's emails."
    s = s & vbCrLf & " ...REMOVE ALL Customer's contact associations."
    s = s & vbCrLf & " ...DELETE ALL Customer's survey orders."
    s = s & vbCrLf & " ...DELETE ALL Customer's inspection test results."
    s = s & vbCrLf & " ...DELETE ALL Customer's inspection orders."
    s = s & vbCrLf & " ...DELETE ALL Customer's customer-site LINKs."
    s = s & vbCrLf
    s = s & vbCrLf & "DO YOU REALLY WANT TO DELETE THE CUSTOMER?"
        
    rtn = MsgBox(s, vbYesNo Or vbExclamation Or vbDefaultButton2, "DELETE Customer")
    If rtn = vbYes Then
        'DELETE THE Customer
        ' Delete ALL contact numbers
        SQL = "DELETE * FROM dbo_CustContactNum WHERE [CustomerID] = " & CStr(vReturnValue)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
        ' Delete ALL Addresses
        SQL = "DELETE * FROM dbo_CustAddress WHERE [CustomerID] = " & CStr(vReturnValue)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
        ' Delete ALL Email
        SQL = "DELETE * FROM dbo_CustEmail WHERE [CustomerID] = " & CStr(vReturnValue)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
        ' Delete ALL CustContact Info
        SQL = "DELETE * FROM dbo_CustContact WHERE [CustomerID] = " & CStr(vReturnValue)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
        ' Delete ALL Survey Orders
        SQL = "DELETE * FROM dbo_SurveyOrder WHERE [CustomerID] = " & CStr(vReturnValue)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
        
        ' iterate over inspection orders and delete test results
        SQL = "SELECT * FROM dbo_InspectionOrder WHERE [CustomerID] = " & CStr(vReturnValue)
        Set rst = CurrentDb.OpenRecordset(SQL, dbOpenSnapshot, dbFailOnError + dbSeeChanges)
        Do While Not rst.EOF
           SQL = "DELETE * FROM dbo_Test WHERE [InspectionOrderID] = " & CStr(rst![InspectionOrderID])
           CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
           rst.MoveNext
        Loop
        rst.Close
        Set rst = Nothing
         
        ' Delete ALL Inspection Orders
        SQL = "DELETE * FROM dbo_InspectionOrder WHERE [CustomerID] = " & CStr(vReturnValue)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
                
        ' Delete ALL CustSite
        SQL = "DELETE * FROM dbo_CustSite WHERE [CustomerID] = " & CStr(vReturnValue)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
    
        ' DELETE .. DELETE .. DELETE .. DELETE .. DELETE .. DELETE
        SQL = "DELETE * FROM dbo_Customer WHERE [CustomerID] = " & CStr(vReturnValue)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
    
        DeleteCustomer = True
        MsgBox "The Customer was DELETED!", vbOKOnly, "DELETE CUSTOMER"
    
    End If

PROC_EXIT:
    On Error Resume Next
    Exit Function

PROC_ERR:
    ' display the system error
    If err.Number <> 0 Then
        msg = ModuleName & " DeleteCustomer" & vbCrLf & _
              "Error # " & CStr(err.Number) & " was generated by " & err.SOURCE & vbCrLf & err.Description
        MsgBox msg, , "Error", err.HelpFile, err.HelpContext
    End If
    
    Resume PROC_EXIT
End Function


    

Public Function DeleteHR() As Boolean
    Dim msg As String
    Dim s As String
    Dim s2 As String
    Dim frm As Form
    Dim mOpenArgs As String
    Dim SQL As String
    Dim v As Variant
    Dim rtn As Integer

    On Error GoTo PROC_ERR
    
    mOpenArgs = "DELETE HR"
    DeleteHR = False
    
    
    
    ' Go grab the ID
    DoCmd.OpenForm "xDlgGoto_DELETE_ID", , , , , acDialog, mOpenArgs
    DoCmd.Close acForm, "xDlgGoto_DELETE_ID"
    
    If (Nz(vReturnValue, 0) > 0) Then
        v = DLookup("[HRID]", "dbo_HR", "[HRID] = " & CStr(vReturnValue))
        If IsNull(v) Then
            'The HR ID doesn't exist.
            Beep
            MsgBox "The HR doesn't exist", vbOKOnly, "DELETE HR FAILED"
            Exit Function
        End If
    Else
        ' NULL VALUE EXIT
        Exit Function
    End If
    
    
    s = vbNullString
    s = "HRID: " & Format(CStr(vReturnValue), "0000")
    ' ----------------------------------
    ' FIX EXCEPTION ERROR ON NULL MISSING CAPTION
    v = DLookup("[FirstName]", "dbo_HR", "[HRID] = " & CStr(vReturnValue))
    s2 = vbNullString
    If Not IsNull(v) Then s2 = CStr(v) & " "
    v = DLookup("[LastName]", "dbo_HR", "[HRID] = " & CStr(vReturnValue))
    If Not IsNull(v) Then
        s2 = s2 & UCase(CStr(v))
    
    If Len(s2) > 0 Then s = s & " " & s2
    Else
        s = s & "A full name wasn't entered for this HR"
    End If
    s = s & vbCrLf & "This action will result in ...."
    s = s & vbCrLf & " ...DELETE ALL HR's contact numbers."
    s = s & vbCrLf & " ...DELETE ALL HR's addresses."
    s = s & vbCrLf & " ...DELETE ALL HR's emails."
    s = s & vbCrLf & " ...DELETE ALL HR's zone info."
    s = s & vbCrLf & " ...DELETE ALL HR's roles assigned."
    s = s & vbCrLf & " ...REMOVE ALL HR's customer contact assoc.."
    s = s & vbCrLf & " ...REMOVE ALL HR's customer's site contact assoc.."
    s = s & vbCrLf & " ...REMOVE ALL HR's survey orders inclusion."
    s = s & vbCrLf & " ...REMOVE ALL HR's inspection orders inclusion."
    s = s & vbCrLf
    s = s & vbCrLf & "DO YOU REALLY WANT TO DELETE THE HR?"
        
    rtn = MsgBox(s, vbYesNo Or vbExclamation Or vbDefaultButton2, "DELETE HR")
    If rtn = vbYes Then
        'DELETE THE HR
        ' Delete ALL contact numbers
        SQL = "DELETE * FROM dbo_HRContactNum WHERE [HRID] = " & CStr(vReturnValue)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
        ' Delete ALL Addresses
        SQL = "DELETE * FROM dbo_HRAddress WHERE [HRID] = " & CStr(vReturnValue)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
        ' Delete ALL Email
        SQL = "DELETE * FROM dbo_HREmail WHERE [HRID] = " & CStr(vReturnValue)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
        ' Delete ALL ZONE Infor
        SQL = "DELETE * FROM dbo_HRZone WHERE [HRID] = " & CStr(vReturnValue)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
        ' Delete ALL Roles
        SQL = "DELETE * FROM dbo_RoleList WHERE [HRID] = " & CStr(vReturnValue)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
        ' Delete ALL CustContact Info
        SQL = "DELETE * FROM dbo_CustContact WHERE [HRID] = " & CStr(vReturnValue)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
        ' Update CustSite info
        SQL = "UPDATE dbo_CustSite SET [SiteContactID] = NULL WHERE [SiteContactID] = " & CStr(vReturnValue)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
        ' Update Survey Orders info
        SQL = "UPDATE dbo_SurveyOrder SET [HRID] = NULL WHERE [HRID] = " & CStr(vReturnValue)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
        ' Update Inspection Orders info
        SQL = "UPDATE dbo_InspectionOrder SET [HRID] = NULL WHERE [HRID] = " & CStr(vReturnValue)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
    
        ' DELETE .. DELETE .. DELETE .. DELETE .. DELETE .. DELETE
        SQL = "DELETE * FROM dbo_HR WHERE [HRID] = " & CStr(vReturnValue)
        CurrentDb.Execute SQL, dbFailOnError + dbSeeChanges
    
        DeleteHR = True
        MsgBox "The HR was DELETED!", vbOKOnly, "DELETE HR"
    
    End If

PROC_EXIT:
    On Error Resume Next
    Exit Function

PROC_ERR:
    ' display the system error
    If err.Number <> 0 Then
        msg = ModuleName & " DeleteHR" & vbCrLf & _
              "Error # " & CStr(err.Number) & " was generated by " & err.SOURCE & vbCrLf & err.Description
        MsgBox msg, , "Error", err.HelpFile, err.HelpContext
    End If
    
    Resume PROC_EXIT
End Function


