Attribute VB_Name = "_DAO_Templates"
Option Compare Database
Option Explicit


'Private Sub Combo217_Change()
'Dim ComboID As String
'Dim ReqID As Long
'Dim dbs As DAO.Database
'Dim qdfUpdateParentExisting As DAO.QueryDef
'
'ReqID = Me.RequestID.Value
'ComboID = Me.Combo217.Column(1)
'
'Set dbs = CurrentDb
'Set qdfUpdateParentExisting = dbs.QueryDefs("UpdateReqExistingParent")
'qdfUpdateParentExisting.Parameters("VBParent").Value = ComboID
'qdfUpdateParentExisting.Parameters("VBReqID").Value = ReqID
'qdfUpdateParentExisting.Execute
'qdfUpdateParentExisting.Close
'DoCmd.Save acForm, "DT2"
'Me.Requery

'End Sub

' EXAMPLES TO CALL A MSSQL EXPRESS database

' SNIP-ITS

Private Sub DAO_Execute_An_Update(a As Control, B As Control)
   Dim db As Database
   Set db = CurrentDb

   DBEngine(0)(0).Execute "UPDATE Table SET Path = '" & a.Value & "' WHERE B = '" & B.Value & "'", dbFailOnError + dbSeeChanges

   db.Close
End Sub


Private Sub DAO_AddNewRecord_Recordset(ByVal aHRID As Long, ByVal aCustomerID As Long)
    Dim strSQL As String, msg As String
    Dim mCustContactID As Long
    Dim rs As DAO.Recordset
    Dim db As DAO.Database
    
    On Error GoTo PROC_ERR
    
    If aHRID > 0 And aCustomerID > 0 Then
        'create a new contactlink record for the customer
        Set db = CurrentDb
        strSQL = "Select * FROM dbo_CustContact"
        ' BSA correct method to use DAO to connect to MSSQL
        Set rs = db.OpenRecordset(strSQL, dbOpenDynaset, dbFailOnError + dbSeeChanges)
        If Not IsNull(rs) Then
            With rs
                .AddNew
                ![HRID] = aHRID
                ![CustomerID] = aCustomerID
                ![CreatedOn] = Date
                ![Caption] = "Contact added on " & Format$(Date, "dd/mmm/yyyy")
                ![ContactTypeID] = 1             'PRIMARY ...
                .Update
                .Bookmark = .LastModified
                mCustContactID = ![CustContactID]
            End With
        End If
    End If
PROC_EXIT:
    'Cleanup
    Set rs = Nothing
    On Error Resume Next
    Exit Sub
PROC_ERR:
    ' display the system error
    If Err.Number <> 0 Then
        msg = "MODULE - #### SUB - ####" & vbCrLf & _
              "Error # " & CStr(Err.Number) & " was generated by " & Err.Source & vbCrLf & Err.Description
        MsgBox msg, , "Error", Err.HelpFile, Err.HelpContext
    End If
    Resume PROC_EXIT
End Sub

