Attribute VB_Name = "_DAO_Templates"
Option Compare Database
Option Explicit


'Private Sub Combo217_Change()
'Dim ComboID As String
'Dim ReqID As Long
'Dim dbs As DAO.Database
'Dim qdfUpdateParentExisting As DAO.QueryDef
'
'ReqID = Me.RequestID.Value
'ComboID = Me.Combo217.Column(1)
'
'Set dbs = CurrentDb
'Set qdfUpdateParentExisting = dbs.QueryDefs("UpdateReqExistingParent")
'qdfUpdateParentExisting.Parameters("VBParent").Value = ComboID
'qdfUpdateParentExisting.Parameters("VBReqID").Value = ReqID
'qdfUpdateParentExisting.Execute
'qdfUpdateParentExisting.Close
'DoCmd.Save acForm, "DT2"
'Me.Requery

'End Sub

' EXAMPLES TO CALL A MSSQL EXPRESS database

' SNIP-ITS

Private Sub DAO_Execute_An_Update(A As Control, B As Control)
   Dim dbs As Database
   Set dbs = CurrentDb

   DBEngine(0)(0).Execute "UPDATE Table SET Path = '" & A.Value & "' WHERE B = '" & B.Value & "'", dbFailOnError + dbSeeChanges

   dbs.Close
End Sub


Private Sub DAO_AddNewRecord_Recordset(ByVal aHRID As Long, ByVal aCustomerID As Long)
    Dim SQL As String, msg As String
    Dim mCustContactID As Long
    Dim rst As DAO.Recordset
    Dim dbs As DAO.Database
    
    On Error GoTo PROC_ERR
    
    If aHRID > 0 And aCustomerID > 0 Then
        'create a new contactlink record for the customer
        Set dbs = CurrentDb
        SQL = "Select * FROM dbo_CustContact"
        ' BSA correct method to use DAO to connect to MSSQL
        Set rst = dbs.OpenRecordset(SQL, dbOpenDynaset, dbFailOnError + dbSeeChanges)
        If Not IsNull(rst) Then
            With rst
                .AddNew
                ![HRID] = aHRID
                ![CustomerID] = aCustomerID
                ![CreatedOn] = Now()
                ![Caption] = "Contact added on " & Format$(Date, "dd/mmm/yyyy")
                ![ContactTypeID] = 1             'PRIMARY ...
                .Update
                .Bookmark = .LastModified
                mCustContactID = ![CustContactID]
            End With
        End If
    End If
PROC_EXIT:
    'Cleanup
    Set rst = Nothing
    On Error Resume Next
    Exit Sub
PROC_ERR:
    ' display the system error
    If err.Number <> 0 Then
        msg = "MODULE - #### SUB - ####" & vbCrLf & _
              "Error # " & CStr(err.Number) & " was generated by " & err.Source & vbCrLf & err.Description
        MsgBox msg, , "Error", err.HelpFile, err.HelpContext
    End If
    Resume PROC_EXIT
End Sub

