Attribute VB_Name = "_REPOSITORY"
Option Compare Database
Option Explicit

Private vReturnvalue As Variant
Const ModuleName As String = "REPOSITORY"

    ' FORMAT DATE STRING FOR SQL EXPRESSION
    ' " (#" & Format(rst![CreatedOn], "mm/dd/yyyy hh:nn") & "#) "

' ######################################################################################
Public Function GENERTIC_FUNCTION(ByVal value As Long) As Boolean
Dim msg As String
    On Error GoTo PROC_ERR
PROC_EXIT:
    On Error Resume Next
    Exit Function

PROC_ERR:
    ' display the system error
    If err.Number <> 0 Then
        msg = ModuleName & " GENERTIC_FUNCTION" & vbCrLf & _
              "Error # " & CStr(err.Number) & " was generated by " & err.Source & vbCrLf & err.Description
        MsgBox msg, , "Error", err.HelpFile, err.HelpContext
    End If
    
    Resume PROC_EXIT
End Function
' ######################################################################################
Public Sub GENERTIC_SUBROUTINE(ByVal aID As Long)
    Dim s As String
    Dim SQL As String
    Dim rst As DAO.Recordset
    Dim dbs As DAO.Database
    Dim msg As String

    On Error GoTo PROC_ERR
    
    If aID > 0 Then
        Set dbs = CurrentDb
        SQL = "Select * FROM dbo_TABLENAME"
        Set rst = dbs.OpenRecordset(SQL, dbOpenDynaset, dbFailOnError + dbSeeChanges)
        If Not IsNull(rst) Then
            With rst
                .AddNew
                ![ID] = aID
                .Update
                .Bookmark = .LastModified
                vReturnvalue = ![ID]
            End With
        End If
    End If
    
PROC_EXIT:
    'Cleanup
    Set rst = Nothing
    Set dbs = Nothing
    On Error Resume Next
    Exit Sub

PROC_ERR:
    ' display the system error
    If err.Number <> 0 Then
        msg = ModuleName & " GENERTIC_SUBROUTINE" & vbCrLf & _
              "Error # " & CStr(err.Number) & " was generated by " & err.Source & vbCrLf & err.Description
        MsgBox msg, , "Error", err.HelpFile, err.HelpContext
    End If
    Resume PROC_EXIT
End Sub


Private Sub CmdDisplayReport_Click()
Dim msg As String
Dim SQL As String
Dim d1 As Date
Dim d2 As Date
Dim s As String

On Error GoTo PROC_ERR

'    vReturnValue = 0
'    TOTRangeNonCore = 0
'    TOTRangeCore = 0
'
'
'    If IsNull(Me.Form![fIntervalSF]![Start]) Then
'        MsgBox "A start date is required", , "Program Attendance Report - ERROR"
'        Exit Sub
'    End If
'
'     'Filter String has dates in AMERICANIZED format
'    d1 = Format(Me.Form![fIntervalSF]![Start], "dd/mm/yyyy")
'    If Not IsNull(Me.Form![fIntervalSF]![End]) Then
'        d2 = Format(Me.Form![fIntervalSF]![End], "dd/mm/yyyy")
'    Else
'        d2 = Date
'    End If
'
'
'    d2 = mdlFunction.AdjustInterval(d2)
'
'     'clear the table
'    SQL = "DELETE * FROM t_ProgAttendance"
'    CurrentDb.Execute (SQL)
'
'    If LoadTable Then
'        s = d1 & "|" & d2 & "|" & CStr(TOTRangeNonCore) & "|" & CStr(TOTRangeCore)
'        DoCmd.OpenReport "RProgramAttendanceReport", acViewReport, "", , acNormal, s
'        vReturnValue = 1
'    End If
    
PROC_EXIT:
    On Error Resume Next
'    Me.Visible = False
    Exit Sub

PROC_ERR:
    ' display the system error
    If err.Number <> 0 Then
        msg = ModuleName & " CmdDisplayReport_Click # " & str(err.Number) & " was generated by " & err.Source & vbCrLf & err.Description
        MsgBox msg, , "Error", err.HelpFile, err.HelpContext
    End If
    vReturnvalue = 0
    Resume PROC_EXIT

    
End Sub




'You can either
'
'Use a query that has parameters and specify values for parameters provided that the query uses parameters.
'
'Dim dbs As DAO.Database
'Dim qdf As DAO.QueryDef
'Dim prm As DAO.Parameter
'Dim rst As DAO.Recordset
'
'Set qdf = CurrentDb.QueryDefs("qry_SomeQueryWithParameters")
'
'qdf.Parameters("SomeParam").Value = "whatever"
'
'Set rst = qdf.OpenRecordset
'or
'
'Specify a query name as the command and use the Filter property on the recordset
'
'    Dim rst As DAO.Recordset
'    Dim rsFiltered As DAO.Recordset
'
'
'    Set rst = CurrentDb.OpenRecordset(qry_SomeQueryWithoutParameters)
'
'    rst.Filter = "field1 > 30"
'    Set rsFiltered = rst.OpenRecordset




'Sub RequeryX2()
'
' Dim dbsNorthwind As Database
' Dim qdfTemp As QueryDef
' Dim prmCountry As Parameter
' Dim rstView As Recordset2
'
' Set dbsNorthwind = OpenDatabase("Northwind.mdb")
' Set qdfTemp = dbsNorthwind.CreateQueryDef("", _
' "PARAMETERS ViewCountry Text; " & _
' "SELECT FirstName, LastName, Country FROM " & _
' "Employees WHERE Country = [ViewCountry] " & _
' "ORDER BY LastName")
' Set prmCountry = qdfTemp.Parameters!ViewCountry
'
' qdfTemp.Parameters!ViewCountry = "USA"
' Debug.Print "Data after initial query, " & _
' [ViewCountry] = USA; " "
' Set rstView = qdfTemp.OpenRecordset
' Do While Not rstView.EOF
' Debug.Print " " & rstView!FirstName & " " & _
' rstView!LastName & ", " & rstView!Country
' rstView.MoveNext
' Loop
'
' ' Change query parameter.
' qdfTemp.Parameters!ViewCountry = "UK"
' ' QueryDef argument must be included so that the
' ' resulting Recordset reflects the change in the query
' ' parameter.
' rstView.Requery qdfTemp
' Debug.Print "Requery after changing parameter, " & _
' "[ViewCountry] = UK"
' Do While Not rstView.EOF
' Debug.Print " " & rstView!FirstName & " " & _
' rstView!LastName & ", " & rstView!Country
' rstView.MoveNext
' Loop
'
' rstView.Close
' dbsNorthwind.Close
'
'End Sub
