Attribute VB_Name = "mdlSiteFind"
Option Compare Database
Option Explicit

Private mRunning As Boolean
Private vReturnvalue As Variant
Private mOpenArgs As String

' +-----------------------------------------------------------
' |
' |  properties for communicating with _SiteFind
' |
Public Property Get Running() As Boolean
Running = mRunning
End Property

Public Property Let ReturnValue(X As Variant)
vReturnvalue = X
End Property

Public Property Get ReturnValue() As Variant
ReturnValue = vReturnvalue
End Property

' +-----------------------------------------------------------
' |
' |  Find Site
' |
Private Sub RunDialog()
Dim msg As String
On Error GoTo PROC_ERR
    mRunning = True
    DoCmd.OpenForm "_SiteFind", , , , , acDialog, mOpenArgs
    DoCmd.Close acForm, "_SiteFind"
    mRunning = False
PROC_EXIT:
    On Error Resume Next
    Exit Sub

PROC_ERR:
    ' display the system error
    If err.Number <> 0 Then
        msg = "mdlSiteFind RunDialog" & vbCrLf & _
        "Error # " & CStr(err.Number) & " was generated by " & err.Source & vbCrLf & err.Description
        MsgBox msg, , "Error", err.HelpFile, err.HelpContext
    End If
    Resume PROC_EXIT
End Sub

