USE [IDFES]
go

-- Standard Alter Table SQL

ALTER TABLE dbo.Site DROP CONSTRAINT DF__Site__IsArchived__546180BB
go
ALTER TABLE dbo.Site ADD CONSTRAINT DF__Site__IsArchived__546180BB DEFAULT ((0)) FOR IsArchived
go
ALTER TABLE dbo.Station DROP CONSTRAINT DF__Station__IsEmpty__1DB06A4F
go
ALTER TABLE dbo.Station ADD CONSTRAINT DF__Station__IsEmpty__1DB06A4F DEFAULT ((0)) FOR IsEmpty
go
ALTER TABLE dbo.Test DROP CONSTRAINT DF__Test__Passed__17AD7836
go
ALTER TABLE dbo.Test ADD CONSTRAINT DF__Test__Passed__17AD7836 DEFAULT ((0)) FOR Passed
go
ALTER TABLE dbo.AddressType DROP CONSTRAINT DF__AddressTy__UsedB__4AB81AF0
go
ALTER TABLE dbo.AddressType DROP CONSTRAINT DF__AddressTy__UsedB__4BAC3F29
go
ALTER TABLE dbo.AddressType ADD CONSTRAINT DF__AddressTy__UsedB__4AB81AF0 DEFAULT ((0)) FOR UsedByHR
go
ALTER TABLE dbo.AddressType ADD CONSTRAINT DF__AddressTy__UsedB__4BAC3F29 DEFAULT ((0)) FOR UsedByCust
go
ALTER TABLE dbo.ContactNumType DROP CONSTRAINT DF__ContactNu__UsedB__4F7CD00D
go
ALTER TABLE dbo.ContactNumType DROP CONSTRAINT DF__ContactNu__UsedB__5070F446
go
ALTER TABLE dbo.ContactNumType ADD CONSTRAINT DF__ContactNu__UsedB__4F7CD00D DEFAULT ((0)) FOR UsedByHR
go
ALTER TABLE dbo.ContactNumType ADD CONSTRAINT DF__ContactNu__UsedB__5070F446 DEFAULT ((0)) FOR UsedByCust
go
ALTER TABLE dbo.ContactType DROP CONSTRAINT DF__ContactTy__UsedB__09A971A2
go
ALTER TABLE dbo.ContactType DROP CONSTRAINT DF__ContactTy__UsedB__0A9D95DB
go
ALTER TABLE dbo.ContactType ADD CONSTRAINT DF__ContactTy__UsedB__09A971A2 DEFAULT ((0)) FOR UsedByHR
go
ALTER TABLE dbo.ContactType ADD CONSTRAINT DF__ContactTy__UsedB__0A9D95DB DEFAULT ((0)) FOR UsedByCust
go
ALTER TABLE dbo.CustSite DROP CONSTRAINT DF__CustSite__IsEnab__114A936A
go
ALTER TABLE dbo.CustSite ADD CONSTRAINT DF__CustSite__IsEnab__114A936A DEFAULT ((0)) FOR IsEnabled
go
ALTER TABLE dbo.EmailType DROP CONSTRAINT DF__EmailType__UsedB__6B24EA82
go
ALTER TABLE dbo.EmailType DROP CONSTRAINT DF__EmailType__UsedB__6C190EBB
go
ALTER TABLE dbo.EmailType ADD CONSTRAINT DF__EmailType__UsedB__6B24EA82 DEFAULT ((0)) FOR UsedByHR
go
ALTER TABLE dbo.EmailType ADD CONSTRAINT DF__EmailType__UsedB__6C190EBB DEFAULT ((0)) FOR UsedByCust
go
