SELECT [Customer].[CustomerID]
     , [Customer].[CustName]
     , [Customer].[CustCode]
     , [Customer].[MYOBID]
     , [Customer].[Note]
     , [Customer].[CreatedBy]
     , [Customer].[CreatedOn]
     , [Customer].[ModifiedBy]
     , [Customer].[ModifiedOn]
     , [Customer].[IsArchived]
     , [CustSite].[CustomerID]
FROM [IDFES].[dbo].[Customer]
    INNER JOIN [CustSite]
        ON [Customer].[CustomerID] = [CustSite].[CustomerID]