SELECT TOP (1000) [EquipTypeID]
      ,[Caption]
      ,[ShortCaption]
      ,[MinorLifeCycle]
      ,[MajorLifeCycle]
      ,[ServiceLevels]
      ,[ServiceInterval]
      ,[CoreGroupID]
  FROM [IDFES].[dbo].[EquipType]