SELECT [Site].[SiteID]
     , [Site].[Note]
     , [Site].[Address]
     , [Site].[CreatedOn]
     , [Site].[IsArchived]
     , [Site].[PostcodeID]
     , [InspectionOrder].[InspectionOrderID]
FROM [IDFES].[dbo].[Site]
    INNER JOIN [CustSite]
        ON [Site].[SiteID] = [CustSite].[SiteID]
    INNER JOIN [InspectionOrder]
        ON [CustSite].[SiteID] = [InspectionOrder].[SiteID]
           AND [CustSite].[CustomerID] = [InspectionOrder].[CustomerID]