SELECT 
		 [StationID]
		,[StationNum]
		,[CircuitBlock]
		,[Location]
		,[Note]
		,[CreatedOn]
		,[LifeCycleSeed]
		,[IsEmpty]
		,[IsManaged]
		,[SiteID]
		,[EquipmentID]
FROM [IDFES].[dbo].[Station] 